// Code generated by MockGen. DO NOT EDIT.
// Source: domain/urlRepo.go

// Package mock_domain is a generated GoMock package.
package mock_domain

import (
	reflect "reflect"
	time "time"
	domain "urlShortener/domain"

	gomock "github.com/golang/mock/gomock"
)

// MockUrlRepoInt is a mock of UrlRepoInt interface.
type MockUrlRepoInt struct {
	ctrl     *gomock.Controller
	recorder *MockUrlRepoIntMockRecorder
}

// MockUrlRepoIntMockRecorder is the mock recorder for MockUrlRepoInt.
type MockUrlRepoIntMockRecorder struct {
	mock *MockUrlRepoInt
}

// NewMockUrlRepoInt creates a new mock instance.
func NewMockUrlRepoInt(ctrl *gomock.Controller) *MockUrlRepoInt {
	mock := &MockUrlRepoInt{ctrl: ctrl}
	mock.recorder = &MockUrlRepoIntMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUrlRepoInt) EXPECT() *MockUrlRepoIntMockRecorder {
	return m.recorder
}

// GetAllValues mocks base method.
func (m *MockUrlRepoInt) GetAllValues() map[string]string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllValues")
	ret0, _ := ret[0].(map[string]string)
	return ret0
}

// GetAllValues indicates an expected call of GetAllValues.
func (mr *MockUrlRepoIntMockRecorder) GetAllValues() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllValues", reflect.TypeOf((*MockUrlRepoInt)(nil).GetAllValues))
}

// GetKey mocks base method.
func (m *MockUrlRepoInt) GetKey(value domain.Urls) (domain.Urls, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetKey", value)
	ret0, _ := ret[0].(domain.Urls)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetKey indicates an expected call of GetKey.
func (mr *MockUrlRepoIntMockRecorder) GetKey(value interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetKey", reflect.TypeOf((*MockUrlRepoInt)(nil).GetKey), value)
}

// SetKey mocks base method.
func (m *MockUrlRepoInt) SetKey(value domain.Urls, expiration time.Duration) (domain.Urls, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetKey", value, expiration)
	ret0, _ := ret[0].(domain.Urls)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SetKey indicates an expected call of SetKey.
func (mr *MockUrlRepoIntMockRecorder) SetKey(value, expiration interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetKey", reflect.TypeOf((*MockUrlRepoInt)(nil).SetKey), value, expiration)
}
